spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    driver-class-name: org.postgresql.Driver
    username: andrey
    password: andrey
server:
  port: 8989
  jpa:
    hibernate:
      ddl-auto: none